#!MANAGED-CONFIG $subs_link interval=43200 strict=true

[General]
loglevel = notify
doh-server = https://1.1.1.1/dns-query, https://dns.google/dns-query
dns-server = 223.5.5.5, 119.29.29.29
skip-proxy = localhost, *.local, 0.0.0.0/8, 10.0.0.0/8, 17.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.168.0.0/16, 224.0.0.0/4, 240.0.0.0/4
ipv6 = true
test-timeout = 5
proxy-test-url = http://www.gstatic.com/generate_204

[Panel]
SubscribeInfo = $subscribe_info, style=info

[Proxy]
$proxies

[Proxy Group]
节点选择 = select, 自动选择, 故障转移, 手动切换, DIRECT, REJECT, $proxy_group
手动切换 = select, $proxy_group
自动选择 = url-test, $proxy_group, url=http://www.gstatic.com/generate_204, interval=600
故障转移 = fallback, $proxy_group, url=http://www.gstatic.com/generate_204, interval=600
AI服务 = select, 节点选择, 自动选择, 故障转移, DIRECT
流媒体 = select, 节点选择, 自动选择, 故障转移, DIRECT
社交媒体 = select, 节点选择, 自动选择, 故障转移, DIRECT
微软服务 = select, 节点选择, 自动选择, DIRECT
苹果服务 = select, DIRECT, 节点选择, 自动选择
广告拦截 = select, REJECT, DIRECT
漏网之鱼 = select, 节点选择, DIRECT

[Rule]
DOMAIN,$subs_domain,DIRECT
DOMAIN-SUFFIX,services.googleapis.cn,节点选择
DOMAIN-SUFFIX,xn--ngstr-lra8j.com,节点选择

RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/OpenAI/OpenAI.list,AI服务
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Netflix/Netflix.list,流媒体
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Disney/Disney.list,流媒体
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list,流媒体
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Telegram/Telegram.list,社交媒体
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Whatsapp/Whatsapp.list,社交媒体
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Facebook/Facebook.list,社交媒体
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list,微软服务
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list,苹果服务
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Advertising/Advertising.list,广告拦截

RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/direct.txt,DIRECT
RULE-SET,https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/proxy.txt,节点选择
GEOIP,CN,DIRECT
FINAL,漏网之鱼
